site_name: Omeka S User Manual
theme:
    name: material
    features:
        - search.suggest
        - search.highlight
    # name: 'readthedocs'
    # custom_dir: 'omeka/'
    # include_homepage_in_sidebar: true
# site_url: 'https://omeka.org/s/'
site_url: "https://nakamura196.github.io/omeka-s-enduser/"
repo_url: 'http://github.com/omeka/omeka-s-enduser'
# extra_css:
#     - css/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - toc:
        permalink: 
nav:
    - index.md
    - accessibility.md
    - s-planning-tips.md
    - install.md
    - admin-dashboard.md
    - glossary.md
    - search.md
    - frontpage.md
    - Sites:
        - sites/index.md
        - sites/site_settings.md
        - sites/site_pages.md
        - sites/site_navigation.md
        - sites/site_resources.md
        - sites/site_users.md
        - sites/site_theme.md
    - Resources:
        - content/items.md
        - content/item-sets.md
        - content/media.md
        - content/vocabularies.md
        - content/resource-template.md
        - content/export.md
    - Admin:
        - admin/users.md
        - admin/jobs.md
        - admin/settings.md
        - admin/assets.md
    - Modules:
        - modules/index.md
        - modules/collecting.md
        - modules/csseditor.md
        - modules/csvimport.md
        - modules/customvocab.md
        - modules/datacleaning.md
        - modules/datavisualization.md
        - modules/datarepositoryconnector.md
        - modules/dspaceconnector.md
        - modules/extractmetadata.md
        - modules/extracttext.md
        - modules/facetedbrowse.md
        - modules/fedoraconnector.md
        - modules/filesideload.md
        - modules/iiifpresentation.md
        - modules/inverseproperties.md
        - modules/itemcarouselblock.md
        - modules/mapping.md
        - modules/metadatabrowse.md
        - modules/ndetermennetwerk.md
        - modules/numericdatatypes.md
        - modules/omekaCimporter.md
        - modules/ositemimporter.md
        - modules/persistentidentifiers.md
        - modules/redactvalues.md
        - modules/resourcemeta.md
        - Scripto:
            - modules/scripto/index.md
            - modules/scripto/scriptoproject.md
            - modules/scripto/themeingScripto.md
            - modules/scripto/scriptoPublicView.md
            - modules/scripto/troubleshootingScripto.md
        - modules/sharing.md
        - modules/uridereferencer.md
        - modules/valuesuggest.md
        - modules/viewprivateresources.md
        - modules/zoterocitation.md
        - modules/zoteroimport.md
    - Miscellaneous:
        - errorLogging.md
        - translateOmekaS.md
        - configuration.md

plugins:
    - i18n:
        docs_structure: suffix
        languages:
            - locale: en
              default: true
              name: English
              build: true
            - locale: ja
              name: Japanese
              build: true
    - search
extra:
  alternate:
    - name: English
      link: /omeka-s-enduser/
      lang: en
    - name: 日本語
      link: /omeka-s-enduser/ja/
      lang: ja